name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: wait-for-mysql
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Fetch Go dependencies
        run: go get .
        working-directory: ./src

      - name: Validate SemVer tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ ! "${TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "The tag ${TAG} is not a valid Semantic Version. Exiting."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PAT }}

      - name: Extract GitHub tag from GITHUB_REF
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest